### PR TITLE
Minimal Backend for CropSync using flask . Fixes #issue- number-9 

### PR DESCRIPTION
**Pull request by Shreyasb1015**
This pull request introduces several enhancements and improvements to the CropSync project. The key contributions include the implementation of backend functionality using Flask, modifications to various HTML templates, updates to the project's database structure, and the creation of responsive forms for login, registration, and account updates.

Changes Made
Modified files: index.html, account.html, login.html, home.html, routes.py, __init__.py, models.py, forms.py, runfile.py, and site.db (database storage for project information).

Mentors are advised to update the database URL in __init__.py to align with their project structure. I have used the following path according to my pc:
sqlite:///C:\\code-files\\CropSync\\site.db

Thank you for considering these contributions. I appreciate your feedback and guidance.You can watch the video below.

https://github.com/cropsync/CropSync/assets/126782359/9f51a712-8197-4fde-baf0-dc5f5cccba0e

### CODE REVIEW

**Comment by KrishGaur1354** [comment]
Some changes can be made; for example, there would be a welcome page that you created as well as login and sign-up page, and after logging in or signing up, you would link to the Cropsync Netify website. I'm closing the PR for now and kindly redoing the PR after making these changes. But I would like to appreciate the changes you made >_<

**Comment by Shreyasb1015** [comment]
Can u eloborate what changes do u want?

**Comment by KrishGaur1354** [comment]
> This pull request introduces several enhancements and improvements to the CropSync project. The key contributions include the implementation of backend functionality using Flask, modifications to various HTML templates, updates to the project's database structure, and the creation of responsive forms for login, registration, and account updates.
> 
> Changes Made Modified files: index.html, account.html, login.html, home.html, routes.py, **init**.py, models.py, forms.py, runfile.py, and site.db (database storage for project information).
> 
> Mentors are advised to update the database URL in **init**.py to align with their project structure. I have used the following path according to my pc: sqlite:///C:\code-files\CropSync\site.db
> 
> Thank you for considering these contributions. I appreciate your feedback and guidance.You can watch the video below.

After users successfully log in or sign up, consider redirecting them to the CropSync Netlify website for a seamless experience. This can be achieved by updating the relevant routes in the routes.py file. Ensure that the redirection is smooth and that users are directed to the appropriate sections or dashboards on the Netlify website.

**Comment by Shreyasb1015** [comment]
After successfully login or sign up, I am redirecting the user to cropsync official age ,as you can watch in the above video.SO what else should I do ? I am unable to undestand the issue .
Please specify

**Pull request closed without merging**
